[build]
  command = "npm run build:netlify"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**"]

# Serve static assets first with proper caching
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Serve images directly
[[redirects]]
  from = "/*.webp"
  to = "/:splat.webp"
  status = 200
  force = true

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200
  force = true

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200
  force = true

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200
  force = true

# CSS and JS files
[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200
  force = true

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200
  force = true

# Main SSR redirect (must be last)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

# Headers for caching
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"