[build]
  command = "npm run build && cp public/_redirects dist/client/_redirects"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**"]