[build]
  command = "npm run build && echo 'Copying all public files...' && cp -r public/* dist/client/ 2>/dev/null || true && echo 'Files copied successfully!' && ls -la dist/client/ && echo 'Build complete!'"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**"]