[build]
  command = "npm run build && cp dist/client/index.html netlify/functions/"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200