[build]
  command = "npm run build && echo '=== Listing all blog images in public ===' && ls -la public/blog*.webp 2>/dev/null || echo 'No blog images found' && echo '=== Copying all files ===' && cp -r public/* dist/client/ && echo '=== Verifying blog images in dist/client ===' && ls -la dist/client/blog*.webp 2>/dev/null || echo 'Blog images not in dist' && echo '=== All files in dist/client ===' && ls -la dist/client/ && echo 'Build complete!'"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**"]